### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/PickAndPaintExtension#15]
@luciemac To avoid confusion, could you delete your project `luciemac/PickAndPaintExtension` and re-fork the one hosted in the `DCBIA-OrthoLab` organization. See https://github.com/DCBIA-OrthoLab/PickAndPaintExtension

The fork graph currently shows this:

![image](https://user-images.githubusercontent.com/219043/70098118-24ffb800-15f9-11ea-8401-208cc1533e47.png)

Thanks :pray:

**Comment by jcfr** [comment]
Ping

**Comment by luciemac** [comment]
@jcfr it is done

<img width="328" alt="Capture d’écran 2019-12-11 à 15 27 34" src="https://user-images.githubusercontent.com/8094456/70629778-cce53900-1c2a-11ea-8ef5-2a719e8ccd3e.png">

**Comment by jcfr** [comment]
Thanks :pray:
